-- 임베디드 모드(메모리 모드)로 DB를 사용할 때,
-- 애플리케이션 로딩 시점에 해당 스크립트(schema.sql 이름 중요!)를 실행해서 테이블을 자동 생성해준다.
drop table if exists item CASCADE;
create table item
(
    id bigint generated by default as identity,
    item_name varchar(10),
    price integer,
    quantity integer,
    primary key (id)
);